version: "3.7"

services:
  # База данных
  postgres:
    container_name: imgames_postgres
    image: postgres:10-alpine
    volumes:
      - db_data:/var/lib/postgresql/data
    env_file: .env

  # Серверная часть
  backend:
    container_name: imgames_nodejs
    build:
      context: .
      dockerfile: backend/Dockerfile
    depends_on:
      - postgres
    command: "node server.js"
    env_file: .env
    volumes:
      - ./backend:/app
    restart: on-failure

  # Сборка фронтенда
  frontend:
    container_name: imgames_frontend
    image: node:14-alpine
    command: npm run serve
    volumes:
      - ./.env:/app/.env:ro
      - ./frontend:/app
    working_dir: /app
    restart: on-failure
    depends_on:
      - backend

  # Веб-сервер
  nginx:
    container_name: imgames_nginx
    image: nginx:alpine
    ports:
      - "8005:80"
    depends_on:
      - backend
      - frontend
    volumes:
      - ./backend/media/:/media/
      - ./backend/staticfiles/:/staticfiles/
      - ./nginx/dev.conf:/etc/nginx/nginx.conf:ro

volumes:
  db_data: {}
