version: "3.3"

volumes:
  postgres_data: {}

services:
  backend:
    container_name: imgames_nodejs
    build:
      context: .
      dockerfile: backend/Dockerfile
    depends_on:
      - postgres
    command: "node server.js"
    env_file: .env
    volumes:
      - ./backend:/app
    restart: on-failure

  postgres:
    image: postgres:10-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file: .env

  nginx:
    build:
      context: .
      dockerfile: nginx/Dockerfile
    ports:
      - "8005:80"
    depends_on:
      - backend
    volumes:
      - ./nginx/prod.conf:/etc/nginx/nginx.conf:ro
